server:
  port: 9000

management:
  security:
    enabled: false

---

spring:
  profiles: dev
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka
  instance:
      preferIpAddress: true

---

spring:
  profiles: docker
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:5000/eureka
  instance:
      preferIpAddress: true
      #leaseRenewalIntervalInSeconds: 1
      #leaseExpirationDurationInSeconds: 2