server:
  port: 8002

management:
  security:
    enabled: false

---

spring:
  profiles: dev
  data:
      cassandra:
        keyspace-name: package_delivery_kepspace
        contact-points: localhost
        schema-action: CREATE_IF_NOT_EXISTS
        port: 9045
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:5000/eureka
  instance:
      preferIpAddress: true


---

spring:
  profiles: docker
  data:
    cassandra:
      keyspace-name: package_delivery_keyspace
      contact-points: cassandra
      schema-action: CREATE_IF_NOT_EXISTS
      port: 9042
      auth:
        username: cassandra
        password: cassandra
eureka:
  client:
    serviceUrl:
      defaultZone: http://service-registry:5000/eureka
  instance:
      preferIpAddress: true
      #leaseRenewalIntervalInSeconds: 1
      #leaseExpirationDurationInSeconds: 2